USE HR

CREATE TABLE IT_WORKER AS
SELECT EMPLOYEE_ID,CONCAT(LAST_NAME, ' ',FIRST_NAME) EMPLEADO,SALARY,0 IVA,0 NETO
FROM EMPLOYEES WHERE 1=2;

DELIMITER $
CREATE OR REPLACE PROCEDURE PR_DEMOCURSOR()
BEGIN
DECLARE VNAME VARCHAR(50);
DECLARE VID INTEGER;
DECLARE VSALARY INTEGER;
DECLARE VIVA INTEGER;
DECLARE VNETO INTEGER;
DECLARE C_CURSOR CURSOR FOR SELECT EMPLOYEE_ID,CONCAT(LAST_NAME, ' ',FIRST_NAME) EMPLEADO,SALARY,0 IVA,0 NETO
FROM EMPLOYEES WHERE JOB_ID='IT_PROG';
OPEN C_CURSOR;
CLOOP: LOOP
 FETCH C_CURSOR INTO VID,VNAME,VSALARY,VIVA,VNETO;
 -- SELECT VID,VNAME,VSALARY,VIVA,VNETO;
 SET VNETO=VSALARY*0.84;
 SET VIVA=VSALARY*0.16;
 INSERT INTO IT_WORKER VALUES(VID,VNAME,VSALARY,VIVA,VNETO);
END LOOP CLOOP;

CLOSE C_CURSOR;
END;
$
DELIMITER ;