USE HR
CREATE TABLE EMP(
IDEMP INTEGER PRIMARY KEY AUTO_INCREMENT,
NOM TEXT,
GENERO ENUM('M','F')
);
 
CREATE TABLE MUJER(
IDEMP INTEGER PRIMARY KEY,
NUMEMBARAZO INTEGER DEFAULT 0,
NUMHIJO INTEGER DEFAULT 0
);

CREATE TABLE HOMBRE(
IDEMP INTEGER PRIMARY KEY,
FUEP DATE
);

ALTER TABLE MUJER ADD CONSTRAINT MUJEREMPFK FOREIGN KEY(IDEMP) REFERENCES EMP(IDEMP);
ALTER TABLE HOMBRE ADD CONSTRAINT HOMBREEMPFK FOREIGN KEY(IDEMP) REFERENCES EMP(IDEMP);

ALTER TABLE HOMBRE ADD COLUMN FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE HOMBRE ADD COLUMN USUARIO TEXT DEFAULT USER();
ALTER TABLE MUJER ADD COLUMN FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE MUJER ADD COLUMN USUARIO TEXT DEFAULT USER();
ALTER TABLE EMP ADD COLUMN FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE EMP ADD COLUMN USUARIO TEXT DEFAULT USER();
DELIMITER $
CREATE OR REPLACE TRIGGER EMPTRG AFTER INSERT ON EMP
FOR EACH ROW
BEGIN
    IF(NEW.GENERO='M') THEN
      INSERT INTO HOMBRE(IDEMP) VALUES(NEW.IDEMP);
    END IF;
    IF(NEW.GENERO='F') THEN
      INSERT INTO MUJER(IDEMP) VALUES(NEW.IDEMP);
    END IF;
    INSERT INTO LOGEMP(IDEMP,OPER,VN) VALUES(NEW.IDEMP,'I',NEW.NOM);
END;
$
DELIMITER ;

INSERT INTO EMP(NOM,GENERO) VALUES('EGAN BERNAL','M');

CREATE TABLE LOGEMP(
IDEMP INTEGER,
OPER CHAR(1),
VA TEXT,
VN TEXT,
FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
USUARIO TEXT DEFAULT USER()
);


DELIMITER $
CREATE OR REPLACE TRIGGER UEMPTRG AFTER UPDATE ON EMP
FOR EACH ROW
BEGIN
   INSERT INTO LOGEMP(IDEMP,OPER,VA,VN) VALUES(OLD.IDEMP,'U',OLD.NOM,NEW.NOM);
END;
$
DELIMITER ;

DELIMITER $
CREATE OR REPLACE TRIGGER DEMPTRG AFTER DELETE ON EMP
FOR EACH ROW
BEGIN
   INSERT INTO LOGEMP(IDEMP,OPER,VA) VALUES(OLD.IDEMP,'D',OLD.NOM);
END;
$
DELIMITER ;

CREATE TABLE PRODUCTO(
IDPROD INTEGER,
NOM TEXT,
CANT INTEGER
);

DELIMITER $
CREATE OR REPLACE TRIGGER IPRODTRG BEFORE INSERT ON PRODUCTO
FOR EACH ROW
BEGIN
  DECLARE ID INTEGER;
  SELECT COUNT(*)+1 INTO ID FROM PRODUCTO;
  SET NEW.IDPROD=ID;
END;
$
DELIMITER ;