USE HR
CREATE OR REPLACE VIEW LISTARTRIGGER AS
SELECT TRIGGER_SCHEMA BD,TRIGGER_NAME
NOMBRE,EVENT_MANIPULATION EVENTO,EVENT_OBJECT_TABLE
TABLA FROM INFORMATION_SCHEMA.TRIGGERS ;

CREATE OR REPLACE VIEW LISTARUTINAS AS
SELECT ROUTINE_SCHEMA BD,ROUTINE_NAME
NOMBRE,ROUTINE_TYPE TIPO FROM
INFORMATION_SCHEMA.ROUTINES;

SELECT * FROM LISTARTRIGGER WHERE BD='HR';
SELECT * FROM LISTARRUTINAS WHERE BD='HR';

CREATE TABLE LOGDEPARTAMENTO(
ID INTEGER,OPERACION CHAR(1),
FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
USUARIO VARCHAR(30),
VALORN TEXT,
VALORV TEXT
);
